".local/share/nvim/site/pack/packer/start/packer.nvim":
  url: https://github.com/wbthomason/packer.nvim
  type: git-repo
  refreshPeriod: "168h"
".oh-my-zsh":
  url: https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz
  type: archive
  stripComponents: 1
  refreshPeriod: "168h"
".oh-my-zsh/custom/plugins/zshrc.d":
  url: https://github.com/mattmc3/zshrc.d.git
  type: git-repo
  refreshPeriod: "168h"
