.oh-my-zsh:
  url: https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz
  type: archive
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/terragrunt:
  url: git@github.com:jleight/terragrunt-zsh-plugin.git
  type: git-repo
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/mise-run:
  url: git@github.com:jleight/mise-run-zsh-plugin.git
  type: git-repo
  refreshPeriod: "168h"
